apiVersion: apps/v1
kind: Deployment

metadata:
  name: flask-api

spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      app: flask-api

  template:
    metadata:
      labels:
        app: flask-api

    spec:
      containers:

      - name: flask-api

        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"

        imagePullPolicy: Always

        ports:
        - containerPort: {{ .Values.containerPort }}