apiVersion: networking.k8s.io/v1
kind: Ingress

metadata:
  name: flask-api-ingress

spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix

        backend:
          service:
            name: flask-api-service

            port:
              number: 5000